### ISSUE TITLE
missing coil ids between CM* and CM*_time delta tables for Pinda

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#1]
25,000+ coils are missing between CM* and CM*_time delta tables for Pinda. This is creating inconsistencies for the feature library.

**Comment by amitdingareNovelis** [comment]
@agrawalch I looked at it again and many coils are still missing. For example

![image](https://user-images.githubusercontent.com/4303278/86655109-77042400-bfb4-11ea-8763-c26ce0e73de6.png)

Here are some additional

![image](https://user-images.githubusercontent.com/4303278/86655218-8d11e480-bfb4-11ea-8568-d70a08d4cc03.png)

**Comment by amitdingareNovelis** [comment]
@guptaad could we change the priority of this to 2?

**Comment by guptaad** [comment]
> @guptaad could we change the priority of this to 2?

@amitdingareNovelis let me check on the workload. Given time data was not put in our scope, I did not assign this a priority. We can discuss and finalize where Time data stands within the list of priorities and current workload.

**Comment by amitdingareNovelis** [comment]
@guptaad  I recommend that we priortize _time data right after Oswego length is done. A lot of the analyses Roberto asked us to do requires this data.

**Comment by khancynthia28** [comment]
@amitdingareNovelis  Now that the time data is loaded do you still see the issue?
