### ISSUE TITLE
Null cg_Gen_PassNumber for yej_cm3 in May and June

### ISSUE THREAD

**Issue by LunaZhangNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#100]
There are 4 coils in May and 470 coils in June that have null cg_Gen_PassNumber:
![image](https://user-images.githubusercontent.com/60981598/90038983-0ecfee80-dc94-11ea-9929-1ecd9428fe1b.png)
![image](https://user-images.githubusercontent.com/60981598/90039025-1b544700-dc94-11ea-968f-49b0b41cbf08.png)

**Comment by khancynthia28** [comment]
Resolved.
