### ISSUE TITLE
Pinda number of coils produced in CM do not match that from PCS

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#17]
[CM_production_data.xlsx](https://github.com/novelis-prod/AA_DE_MachineProcessData/files/4559670/CM_production_data.xlsx)

@agrawalch @WilberDelbrison  pulled the number of coils from PCS and we compared those to what in the data lake in the month of April. We see discrepancies.

**Comment by khancynthia28** [comment]
Closing this as resolved. This check is now included in the Inventory Dashboard. Please see MES v DE Table Coil Count tab.
