### ISSUE TITLE
Pinda HFM sync lengths zeros

### ISSUE THREAD

**Issue by SauravNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#22]
While trying to join the data between HFM and CM1, 

![image](https://user-images.githubusercontent.com/58706689/81226845-7ac9f900-8fb9-11ea-8929-6ad29a3ee94a.png)

![image](https://user-images.githubusercontent.com/58706689/81226806-6be34680-8fb9-11ea-87b1-94b4ed519979.png)

we noticed that sync lengths are all zeros in HFM for 2020 data.
![image](https://user-images.githubusercontent.com/58706689/81226662-30487c80-8fb9-11ea-9d50-7900299e72c6.png)

There are other inconsistencies as well.
1. Missing days
2. Significantly different number of coils in HFM, HRM, and CM for different months

**Comment by guptaad** [comment]
@khancynthia28 to test.

**Comment by khancynthia28** [comment]
@agrawalch Can we close?

**Comment by agrawalch** [comment]
@khancynthia28 
yes
