### ISSUE TITLE
sync length missing from the time delta tables.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#30]
sync length does not exist in the _time tables. This makes joining the tables across machine centers difficult.

![image](https://user-images.githubusercontent.com/4303278/83181690-3bdc1e80-a0f3-11ea-965c-1771fa253cb6.png)

**Comment by khancynthia28** [comment]
@amitdingareNovelis Can we close this one?

**Comment by amitdingareNovelis** [comment]
Yes. Closing.
