### ISSUE TITLE
The yej_cm3 and yej_cm2 does not have cg_gen_passnumber column

### ISSUE THREAD

**Issue by guptaad** [novelis-prod/Digital-CoE-Operations-Data---Public#31]
The yej_cm3 is expected to have the pass number column.

**Comment by amitdingareNovelis** [comment]
I didn't find pass number in yej_cm3.

![image](https://user-images.githubusercontent.com/4303278/84808772-2ca40e80-afd7-11ea-9548-0f0c313329fb.png)

**Comment by BrentR2020** [comment]
Krishna will add the column today.

**Comment by guptaad** [comment]
![image](https://user-images.githubusercontent.com/53626261/84945229-08b6fa80-b0b5-11ea-8ee7-c4979a2817ff.png)

The pass number in the cold mill is added and showing up. The historical data updates will fix the null values in the pass number.
