### ISSUE TITLE
The yej_hrm does not have cg_Gen_TotalPass

### ISSUE THREAD

**Issue by guptaad** [novelis-prod/Digital-CoE-Operations-Data---Public#32]
The HRM does not have Total Pass column - cg_Gen_TotalPass

**Comment by zennet-novelis** [comment]
@guptaad 
Krishna and I talked about this for Oswego CM72 today. Looks like we won't be able to define it because it's not available. He's going to open this as another issue.

**Comment by BrentR2020** [comment]
ChangHyuck has tested and validated, this should be closed.

**Comment by guptaad** [comment]
> @guptaad
> Krishna and I talked about this for Oswego CM72 today. Looks like we won't be able to define it because it's not available. He's going to open this as another issue.

**Comment by guptaad** [comment]
![image](https://user-images.githubusercontent.com/53626261/84927472-e3b58e00-b09a-11ea-8baf-1fd0797cc4a4.png)


I am able to see the cg_GenTotalPass and the data looks correct.

**Comment by guptaad** [comment]
With the latest finding. Closing this issue.
