### ISSUE TITLE
Timestamp in PI data string type rather than timestamp

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#35]
For each plant and machine center for PI data the Timestamp column is a string. 

![image](https://user-images.githubusercontent.com/58708978/83898326-c1c81d00-a724-11ea-905c-9e541ca51933.png)
![image](https://user-images.githubusercontent.com/58708978/83898349-cbea1b80-a724-11ea-8585-9b7452c52824.png)
![image](https://user-images.githubusercontent.com/58708978/83898379-d6a4b080-a724-11ea-80d9-c6e3ab32acbb.png)

**Comment by khancynthia28** [comment]
@amitdingareNovelis @guptaad Timestamp columns for all three plants have been converted to type timestamp. Closing this ticket. Please reopen if needed. Thanks!
