### ISSUE TITLE
The column cg_gen_passnumber does not exist in CM88

### ISSUE THREAD

**Issue by guptaad** [novelis-prod/Digital-CoE-Operations-Data---Public#36]
![image](https://user-images.githubusercontent.com/53626261/84145395-c98b0880-aa27-11ea-9b97-c2579f48d715.png)

**Comment by guptaad** [comment]
> @BrentR2020 @guptaad
> I've got a question about Priority 1 meaning, aside from this issue per se.
> 
> It seems that we shouldn't stop working on issues that would affect our deliverables in the AGW Weekly Communication to fix this issue. Suppose that this issue took two days to fix and caused us to miss delivery of a goal in the AGW Weekly then we would prefer to meet our goals. Is that correct?
> 
> Usually P1 wants to be reserved for a "Stop Everything and Fix This". In the case of this issue, it should only take about an hour to fix and the other deliverables are done so it's not a problem.
> 
> I didn't have time to raise this clarification on how we want to use the issue tracker in our meeting this morning.

@zennet-novelis , We discussed this in our daily call a couple of times. Please let me if you need to discuss.

**Comment by guptaad** [comment]
I understand that the code is complete for this, and we are waiting to test this data once the IBA DAT Coordinator issues are resolved.

**Comment by BrentR2020** [comment]
Need to get the pipeline working and uploads to D06.

**Comment by zennet-novelis** [comment]
We should have 6 days of data to validate this on.

**Comment by zennet-novelis** [comment]
@KrishnaMaddipati Validated that this is fixed and can be closed.

**Comment by guptaad** [comment]
![image](https://user-images.githubusercontent.com/53626261/85319425-7ab18a00-b48f-11ea-9d08-aae69daea9b6.png)


The Pass# are showing up now. Closing this issue.
