### ISSUE TITLE
sync length intervals

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#37]
Question,  but possible bug.

Is sync_length supposed to be at every 0.25 interval or can there be jumps as seen below?

![image](https://user-images.githubusercontent.com/58708978/84155495-605ec180-aa36-11ea-8350-99f866ac7e0b.png)

**Comment by guptaad** [comment]
@RyanNovelis this is possible when there is no signal captured for the meter length of the coil. This should be rare. 
Is this something in Pinda?
Can you please give me the coil# for this?

**Comment by RyanNovelis** [comment]
@guptaad This is from opsentprodg2.pba_cm3 and the coil# is 71901.

**Comment by amitdingareNovelis** [comment]
@guptaad any update on this?

**Comment by amitdingareNovelis** [comment]
Depends on the actual length. This is valid.
