### ISSUE TITLE
Entry-Head-Discard values are negative in coil lineage table

### ISSUE THREAD

**Issue by agrawalch** [novelis-prod/Digital-CoE-Operations-Data---Public#40]
Entry-Head-Discard values are negative in coil lineage table
![image](https://user-images.githubusercontent.com/53792688/84191558-a59ae780-aa66-11ea-8895-11147eab3630.png)

**Comment by guptaad** [comment]
Demoting to 2nd Priority as some of this data is expected. We may need to catch these during the L1 or L2 validation checks.

**Comment by khancynthia28** [comment]
Closing this as resolved.
