### ISSUE TITLE
Oswego Delta tables is missing CM72 data. When will it be available?

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#42]

**Comment by zennet-novelis** [comment]
CM72 Coil ID was fixed in #44 and reprocessed on Friday.

@KrishnaMaddipati said the month of May should be available in the Enterprise Zone June 16.

**Comment by zennet-novelis** [comment]
@guptaad 
Krishna said this was ready yesterday.

**Comment by BrentR2020** [comment]
This one should also be closed.

**Comment by guptaad** [comment]
Data is loaded.
