### ISSUE TITLE
Oswego CM72 coil id invalid in parquet length 

### ISSUE THREAD

**Issue by KrishnaMaddipati** [novelis-prod/Digital-CoE-Operations-Data---Public#44]
The coil id values for OSW CM72   has a 6 digit string(031823)  instead of a 7 digit string. 

![CM72](https://user-images.githubusercontent.com/62263802/84538831-4afcc800-acc0-11ea-8e7c-da573d882137.JPG)

![image](https://user-images.githubusercontent.com/62263802/84539091-d0807800-acc0-11ea-850b-dfd40a4b2ed0.png)

Looks like the last digit of the coil id was getting ripped off during parquet conversion.
@zennet-novelis Can you please validate the PDO of OSW CM72.

**Comment by zennet-novelis** [comment]
Fixed and testing on CM72 May 8 parquet length.

**Comment by BrentR2020** [comment]
This one should be closed, it has been fixed, validated and tested.

**Comment by guptaad** [comment]
The correct data is loaded.
