### ISSUE TITLE
OSW CM72 doesn't have cg_Gen_TotalPass in parquet length

### ISSUE THREAD

**Issue by KrishnaMaddipati** [novelis-prod/Digital-CoE-Operations-Data---Public#45]
CM72 parquet length data doesn't have cg_Gen_TotalPass signal.

![image](https://user-images.githubusercontent.com/62263802/84541825-1db31880-acc6-11ea-99f9-b70eed344353.png)

**Comment by zennet-novelis** [comment]
For CM72, it doesn't look like this information is available in IBA. Only via MIS. We can ask Oswego to be sure as I'm just guessing based on the IBA file and PDO.

I didn't check CM88.

**Comment by amitdingareNovelis** [comment]
We will need this information. It has to be available somewhere.

**Comment by zennet-novelis** [comment]
It is definitely available in MIS and a few other systems. But not in the IBA system so we can't fix it in a PDO. at least that's what I'm guessing. DE Rules can implement it another way.

**Comment by guptaad** [comment]
@KrishnaMaddipati @zennet-novelis  @amitdingareNovelis - the TotalPass information comes from HRM. The CM will only have the PassNumber, not TotalPass.

The CM72 does have the cg_Gen_PassNumber. Did I get something wrong?

![image](https://user-images.githubusercontent.com/53626261/84784062-e095a180-afb7-11ea-99c8-bfef57d0de5e.png)

**Comment by BrentR2020** [comment]
Can we close this issue?  Nobody else on the team can close this except Adarsh and Amit.

**Comment by guptaad** [comment]
Closing as the data is available.
