### ISSUE TITLE
Every single coil in HFM has a metal code = '1000000000000000'

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#46]
This makes the data unusable for downstream processes.
![image](https://user-images.githubusercontent.com/4303278/84546863-43451f80-acd0-11ea-8efd-53083945e095.png)

**Comment by guptaad** [comment]
@KrishnaMaddipati - as discussed, please change the logic to populate the metal_code from the combination of the L2 and MES systems. The metal_code should be generated based on the coil_id from L2 data or MES data, whichever comes first.

Once you have this logic done, you will need to update the historical data.

**Comment by amitdingareNovelis** [comment]
same problem also exists for CM.

![image](https://user-images.githubusercontent.com/4303278/85033636-2cc71a00-b14f-11ea-9a45-26666aa81103.png)

**Comment by agrawalch** [comment]
metal_code is added to all the coils from June month as of yesterday present in the cloud. For those same coils, if there are HFM and CM88 coils, they are also updated with the metal_code. This update in oswego machine center table is done in the production environment. However, coil_index table is present in the dev. So you can access machine center coils from production environment for training or demo.
The new metal_code creation will have to implemented in production and we will start working on this today.

**Comment by KrishnaMaddipati** [comment]
@amitdingareNovelis @guptaad  all the metal codes for OSW machine centers were updated and the new metal_code logic was implemented in production.

![image](https://user-images.githubusercontent.com/62263802/86207223-0b493380-bb3c-11ea-90b3-fa03b545628c.png)

![image](https://user-images.githubusercontent.com/62263802/86207251-1e5c0380-bb3c-11ea-8186-37de4e2afb0b.png)

![image](https://user-images.githubusercontent.com/62263802/86207303-40ee1c80-bb3c-11ea-9d69-fe27950e9092.png)

**Comment by guptaad** [comment]
@khancynthia28 to test

**Comment by khancynthia28** [comment]
@amitdingareNovelis - Issue seems to have been resolved. Please see test results below:
![image](https://user-images.githubusercontent.com/34836475/86310303-b664f600-bbeb-11ea-91c2-044bbcb1f3ed.png)


Please close if the results are confirmed.

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87572639-da1f4600-c699-11ea-9459-ec2d54718009.png)

@amitdingareNovelis @guptaad @BrentR2020 @KrishnaMaddipati - This seems to now be resolved. I'm closing this ticket. Please reopen if needed. Thanks.
