### ISSUE TITLE
OSW HRM length parquet doesn't have cg_Gen_PassNumber signal 

### ISSUE THREAD

**Issue by KrishnaMaddipati** [novelis-prod/Digital-CoE-Operations-Data---Public#47]
OSW HRM length parquet have TotalPass signal, but it doesn't have PassNumber signal.

![image](https://user-images.githubusercontent.com/62263802/84676424-7e776680-aefb-11ea-8bfd-8d053a9899a6.png)

**Comment by zennet-novelis** [comment]
**cg_Gen_PassNumber** was not implemented in the parquet length PDO.

We have two signals already in the PDO
check Pass Counter [5:20]
vd_PassNumber [9:0]
But they have not been selected for export and are not in the parquet length.

**Comment by zennet-novelis** [comment]
> So this is just a matter of adding the signal to the PDO?
If yes, please go ahead.

I can implement the cg_gen_passnumber expression, and enable the export of the pass number signals in the PDO.
Then we need to reprocess May - June data and validate.

**Comment by KrishnaMaddipati** [comment]
Can we get PassNumber values from MES or anywhere else?

If so, then we don't need to reprocess the data again, we can update the values using that data for historical data (already processed data).

**Comment by guptaad** [comment]
![image](https://user-images.githubusercontent.com/53626261/84780695-dffb0c00-afb3-11ea-9ce3-2e093f507ba5.png)

@KrishnaMaddipati the data is showing the pass# in the OSW HRM for all coils. Can you confirm if this is still the issue?

**Comment by guptaad** [comment]
We have the data for the TotalPass.
