### ISSUE TITLE
Oswego Melter data - containing multiple duplicate batch & master_batch ids

### ISSUE THREAD

**Issue by ethanchaNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#50]
![image](https://user-images.githubusercontent.com/60716978/84797470-e0050700-afc7-11ea-92d1-2fc02ec5eab0.png)
![image](https://user-images.githubusercontent.com/60716978/84798002-70dbe280-afc8-11ea-9113-d215acbee6f6.png)

Hello, while validating data on our end, I noticed that there are multiple duplicate batch ids & master_batch_ids for Oswego Melter, Holder, and (I assume the situation may be same for) Caster. (opsentprodg2.osw_melter/holder/caster)

We'd appreciate it if you could shed some light on this. Thanks!

**Comment by khancynthia28** [comment]
@ethanchaNovelis Can you please test now. Thanks.

**Comment by ethanchaNovelis** [comment]
Thanks, Cynthia.
![image](https://user-images.githubusercontent.com/60716978/87166388-811a7100-c299-11ea-9f71-e5848eaa542e.png)

But still gives me a duplicate Batch_ID and master_batch_id

**Comment by khancynthia28** [comment]
@ethanchaNovelis Please remove month and day from the group by clause as that might cause multiple entries for the same batch id in the case when a batch's records span over multiple days. 

![image](https://user-images.githubusercontent.com/34836475/87237882-90004100-c3c9-11ea-8a72-f577dc1cfd65.png)

**Comment by khancynthia28** [comment]
@ethanchaNovelis A record in the PI tables will be considered duplicate when the same Timestamp occurs for the same batch or same machine. By that definition it seems there are no duplicate records in the melter, holder and caster tables. Can we close this?

**Comment by BrentR2020** [comment]
resolved
