### ISSUE TITLE
metal code is not populated for many coils in May and June for Yeongju

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#51]
![image](https://user-images.githubusercontent.com/4303278/84810307-2b73e100-afd9-11ea-83ae-8905c2a368c1.png)

**Comment by guptaad** [comment]
@KrishnaMaddipati and @changhyucklee - I think this is the same issue that we are working on with Oswego data where we want the metal_code to be generated at the time of coil arrival. Once Oswego is complete, please use the same method to implement this in YJ.

**Comment by guptaad** [comment]
@khancynthia28 to test

**Comment by khancynthia28** [comment]
@agrawalch The issue seems to be resolved for HRM, CM2 and CM3 but still not resolved for HFM --
![image](https://user-images.githubusercontent.com/34836475/86311248-f0cf9280-bbed-11ea-80dc-85a88d0420a1.png)

**Comment by KrishnaMaddipati** [comment]
HFM metal code problem was resolved.
![image](https://user-images.githubusercontent.com/62263802/86354250-af170a00-bc36-11ea-95fa-9a8eaa7ac283.png)

**Comment by khancynthia28** [comment]
@amitdingareNovelis  Can we close this?

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87572435-844a9e00-c699-11ea-916e-f829c1dcb370.png)

@amitdingareNovelis @guptaad @BrentR2020 @KrishnaMaddipati  - The issue seems to be now resolved. I'm closing the ticket. Please reopen if needed.
