### ISSUE TITLE
coils stopped coming to data lake for CM72 and CM88

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#54]
![image](https://user-images.githubusercontent.com/4303278/85030368-5d0cb980-b14b-11ea-8e82-53a34353f597.png)

**Comment by amitdingareNovelis** [comment]
Data seems to have caught up, but the coil numbers appear low.

**Comment by zennet-novelis** [comment]
@amitdingareNovelis 
Data has not caught up yet for CM88, CM72 but should within 3 days. I can ping you or update here when it does.

**Comment by zennet-novelis** [comment]
@amitdingareNovelis 
CM72 and CM88 are coming into the data lake again.
You can close this issue.

The numbers will be low until we do a backfill.

**Comment by guptaad** [comment]
With the coils showing up in the delta tables. closing this issue.

**Comment by amitdingareNovelis** [comment]
@guptaad As a practice, only the person who opened the issue should be allowed to close it as the person can confirm whether the issue is really fixed or not.

In this case, for CM72, the last day of data in the data lake is 05/22 i.e. more than a month old. See below.

![image](https://user-images.githubusercontent.com/4303278/85858341-79cb7180-b789-11ea-8de4-8fd6ba55a963.png)


Also, for CM88, the data hasn't come after 06/22.

![image](https://user-images.githubusercontent.com/4303278/85858385-8ea80500-b789-11ea-8eba-8925be0cabe6.png)

Reopening.

**Comment by zennet-novelis** [comment]
@KrishnaMaddipati 
Can you update the delta lake with the latest sources?

**Comment by guptaad** [comment]
@khancynthia28 to test.

**Comment by khancynthia28** [comment]
![cm72](https://user-images.githubusercontent.com/34836475/86281479-97df0a80-bbab-11ea-93af-d95379123b08.PNG)

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/86281581-c78e1280-bbab-11ea-957e-83eea6a7f127.png)

**Comment by khancynthia28** [comment]
We now have data till end of June in Delta tables for both CM72 and CM88. This issue can now be closed.

**Comment by amitdingareNovelis** [comment]
Confirmed. One question: CM72 goes only until 06/29 while CM88 goes till 06/30. Any reason for that?
