### ISSUE TITLE
same coil, metal code and pass number for CM72 are received on multiple days

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#56]
![image](https://user-images.githubusercontent.com/4303278/85035105-d0fd9080-b150-11ea-99fd-86fdcbdcbcd1.png)

**Comment by amitdingareNovelis** [comment]
This may not be an issue once the metal codes are populated, but wanted to have it open. We can close it once we populate the metal codes.

**Comment by guptaad** [comment]
This may be the same case as we found in Pinda that the coil_id is manually entered and it is incorrect. Once the Metal_Code is correctly populated, we need to check on this.

**Comment by khancynthia28** [comment]
@amitdingareNovelis @KrishnaMaddipati @zennet-novelis - Now that the metal code is populated is this issue still valid?

**Comment by khancynthia28** [comment]
Closing this one. Please reopen if needed.

**Comment by khancynthia28** [comment]
6 such coils still exist:

![image](https://user-images.githubusercontent.com/34836475/88389480-98228e00-cd84-11ea-85e9-d99e03c4dffe.png)

**Comment by khancynthia28** [comment]
Keeping the issue closed still since the anomaly is below our thresh hold.

**Comment by KrishnaMaddipati** [comment]
we are getting multiple files with same coil id and pass number on different days. In below screenshot coil id 1744696 has got 35 files with same pass number value.

![image](https://user-images.githubusercontent.com/62263802/88428271-9677bb00-cdc2-11ea-81f5-12b87246b910.png)

@zennet-novelis -- As we discussed, here is path for the  coil id 1744696 file which was uploaded on 07/16 'landing/oswego/iba/standard/material_length/300_cm1_cm72/2020/07/16/174469-6 -1 - X621_35.parquet'. 

@zennet-novelis  Please take a look at those files.
