### ISSUE TITLE
For Oswego, many coils exist in CM, but not in HFM

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#58]
![image](https://user-images.githubusercontent.com/4303278/85060922-01a2f180-b174-11ea-90e4-40ce73d6de50.png)

Above is just one example, but there are 692 coils that satisfy this condition.

**Comment by guptaad** [comment]
this is possible as the historical data loads progress.

**Comment by amitdingareNovelis** [comment]
The issue is not limited to historical data. I found many coils (469) where the issue exists even for June 2020.,

![image](https://user-images.githubusercontent.com/4303278/85327336-c3237480-b49c-11ea-9eec-eb19a5d4db8c.png)

**Comment by amitdingareNovelis** [comment]
@guptaad given that this is true for June, should this be marked as Priority 1?

**Comment by khancynthia28** [comment]
Closing this as invalid since HFM data is not yet available. Please reopen if issue exists in the future.
