### ISSUE TITLE
For Oswego 662 coils exist in HRM but not in HFM

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#59]
Here is an example
![image](https://user-images.githubusercontent.com/4303278/85070565-066fa180-b184-11ea-95bb-51a9084d9d83.png)

**Comment by guptaad** [comment]
This is possible as the historical loads catch up to all the data.

**Comment by amitdingareNovelis** [comment]
This is also true for June data. 
![image](https://user-images.githubusercontent.com/4303278/85408760-f1ec2a00-b532-11ea-827a-22762ed98d46.png)

**Comment by amitdingareNovelis** [comment]
@guptaad given that this is true for June, should this be marked as Priority 1?

**Comment by khancynthia28** [comment]
Closing this as HM data is not yet available. Please reopen if issue exists in the future.
