### ISSUE TITLE
Pinda CM has many coils with sync length < 0

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#60]
![image](https://user-images.githubusercontent.com/4303278/85244333-4fd52080-b412-11ea-9cb5-567f2ff1089b.png)

**Comment by amitdingareNovelis** [comment]
Exact number is 638 so far.

**Comment by guptaad** [comment]
This is done. 
@amitdingareNovelis , @guptaad  and @khancynthia28 to test this data now.

**Comment by khancynthia28** [comment]
@amitdingareNovelis  Please see test results --
![image](https://user-images.githubusercontent.com/34836475/86310446-1a87ba00-bbec-11ea-9eae-51eb9567fd53.png)


Please close if results are confirmed.

**Comment by amitdingareNovelis** [comment]
confirmed. Closing.
