### ISSUE TITLE
Oswego CM88: Null cg_gen_passnumber

### ISSUE THREAD

**Issue by guptaad** [novelis-prod/Digital-CoE-Operations-Data---Public#61]
![image](https://user-images.githubusercontent.com/53626261/85319546-af254600-b48f-11ea-9d01-8ce3a4ea6c06.png)

There are 540 coils where the pass# is not calculated. This needs to be manually updated.

**Comment by zennet-novelis** [comment]
Likely duplicate of #55

**Comment by guptaad** [comment]
This is a duplicate of #55; so closing this one
