### ISSUE TITLE
Missing values in HFM coil68644 June 3, 2020

### ISSUE THREAD

**Issue by zhiyu-novelis** [novelis-prod/Digital-CoE-Operations-Data---Public#63]
I randomly downloaded a coil dataset from aldsgen2 for eagle anomaly detection, and it seems like there are lots of missing values, many are in the last row. 

<img width="546" alt="coil68644nas" src="https://user-images.githubusercontent.com/65193309/85604860-ab282e00-b61f-11ea-8e3b-7accf52ea099.png">

<img width="218" alt="na_counts" src="https://user-images.githubusercontent.com/65193309/85604872-ac595b00-b61f-11ea-8082-81505cdb38e2.png">

**Comment by guptaad** [comment]
Are you looking at the Pinda data?
Some of the data is expected to have null values. It depends on the coil loaded in the mill or not.

**Comment by amitdingareNovelis** [comment]
@zhiyu-novelis are we good to close this?

**Comment by zhiyu-novelis** [comment]
@guptaad Yes, got it. Just wanted to bring this to your attention in case anything needs to be done.
@amitdingareNovelis Yep, good to close now.

**Comment by amitdingareNovelis** [comment]
Closing.
