### ISSUE TITLE
Repeated eg_RelativeLength in CM2 and CM3 causing repeats in actual_pos

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#65]
In both CM2 and CM3 there are repeats within eg_RelativeLength per cg_Gen_PassNumber causing duplication within CM2 and data inconsistencies within CM3

CM2
![image](https://user-images.githubusercontent.com/58708978/85629202-6c09d500-b63f-11ea-8772-bcc0386a1927.png)

CM3
![image](https://user-images.githubusercontent.com/58708978/85629044-25b47600-b63f-11ea-8a71-4e14077eb666.png)
![image](https://user-images.githubusercontent.com/58708978/85629062-2cdb8400-b63f-11ea-83eb-f1908f32112e.png)

**Comment by guptaad** [comment]
@RyanNovelis I will need to understand this a little better. I discussed a little with Amit, but I am looking to understand the formula for actual_pos and how is it different (or differently used) compared to ActualLength.

**Comment by RyanNovelis** [comment]
@guptaad per conversations with @agrawalch and Felipe Rocha there are instances where eg_LengthIndex repeats due to rounding in the dat to parquet conversion. So I was told by Felipe that we could multiply eg_RelativeLength with eRg_TotalLength to get the actual position of the coil.

actual_pos = eg_RelativeLength * eRg_TotalLength

example of the rational below:
![2020_03_10_16_13_41_delta_testing_Databricks](https://user-images.githubusercontent.com/58708978/85869319-85269900-b799-11ea-9e2c-b4130038f6c2.png)

**Comment by amitdingareNovelis** [comment]
@guptaad @agrawalch any update on this? I want Ryan to run aggregations for Pinda just so we can have that data ready for the hands-on training. Appreciate if you could look into this.

**Comment by amitdingareNovelis** [comment]
@agrawalch per our discussion, I looked into it and there are many coils with this issue. Here is an example.

![image](https://user-images.githubusercontent.com/4303278/86661650-ecbebe80-bfb9-11ea-86d6-b1a52f637f5b.png)

Here is the query to get the numbers

![image](https://user-images.githubusercontent.com/4303278/86661753-06f89c80-bfba-11ea-81a3-06696fd7041b.png)

@guptaad could we change the priority of this to 1?

**Comment by guptaad** [comment]
@amitdingareNovelis can we discuss this as well? This data come as-is from IBA systems so I need to understand what can we change here.

**Comment by amitdingareNovelis** [comment]
> @amitdingareNovelis can we discuss this as well? This data come as-is from IBA systems so I need to understand what can we change here.

I talked to @agrawalch yesterday. He was expecting this to happen for a few coils only, but as you can see, it is happening for a lot of coils. How can you have multiple rows for the relative length?
