### ISSUE TITLE
Change to Power BI Data Inventory report

### ISSUE THREAD

**Issue by nahoxie** [novelis-prod/Digital-CoE-Operations-Data---Public#66]
Add Oswego plant to data inventory detail tab.  Currently there are only Pinda and YJ.

https://app.powerbi.com/groups/me/apps/088c1570-b79c-4f1f-bad7-7bb8a0dfed32/reports/627ecebe-4475-4eec-9433-144561314c6e/ReportSection7a4c3061331850b33ca7

**Comment by khancynthia28** [comment]
@nahoxie Data for Oswego is now available in the Inventory Dashboard. Can we close this one?

**Comment by khancynthia28** [comment]
@nahoxie Closing this one. Please reopen if needed
