### ISSUE TITLE
cg_Gen_Coilid wrong in some Pinda HFM parquets 

### ISSUE THREAD

**Issue by hebernogueira** [novelis-prod/Digital-CoE-Operations-Data---Public#67]
Hello, 

As found already other cases, some parquets have cg_Gen_Coilid not correct.
Roberto Q. and Chirag worked on that, but it seems to keep having the same issue. 
Need some investigation about the source of the problem. Please, check screenshot attached.
For now, I am using code workaround but might be affecting others.

Thanks you very much.
Heber

![2020-06-27 13_55_58-Window](https://user-images.githubusercontent.com/61158959/85927716-43235300-b87e-11ea-8c19-8b4e96b0a910.png)

**Comment by guptaad** [comment]
Based on earlier emails, I think the operator at the machine center may mis-key the coil_id. In such cases, we get bad data from the source and this needs to be part of the Level2 Data Validation checks.

@agrawalch - use the coilID from file name and compare that to the dat content. If they do not match then reject the coil. - Level 1 data validation rule.

**Comment by hebernogueira** [comment]
Hi @guptaad , 
according to Roberto the moment we are registering the cg_Gen_Coilid is affecting that. In the actual pdo, we look after the end of load in Stand F4 (exactly 15seconds) but the next coil is already on the entry shear (and this is the trigger to start recording new coil on IbaCoordinator). 
The operator has no option to enter or type in the coil id by mistaken. When we look the raw file than it is clear the issue.
So if we change the pdo to look the Coil id in the middle of coil (as Roberto did) then the issue might be solved.
![cg_gen_coilid](https://user-images.githubusercontent.com/61158959/86056716-3f393180-ba34-11ea-981b-c4403ed38638.png)

**Comment by guptaad** [comment]
@hebernogueira - the mis-key comment was captured based on the CM data; and it is possible that it is not happening in HFM.
Chirag has the list of priorities not and he will have this work cut for him during the next week.

**Comment by hebernogueira** [comment]
Chirag replaced the pdo file from Roberto in the VM.
