### ISSUE TITLE
cg_Gen_Alloy 518213 instead of 5182M Pinda's HFM files

### ISSUE THREAD

**Issue by hebernogueira** [novelis-prod/Digital-CoE-Operations-Data---Public#68]
Hi,

We are getting alloy equals to 518213 in some coils but this is an invalid alloy. The correct should be 5182M.
Maybe there is a correct field on the raw data which could be used as correct address for cg_Gen_Coilid.
Is it possible to evaluate the signal cg_Gen_Alloy?
Thanks,

Heber

![cg_gen_alloy Pinda](https://user-images.githubusercontent.com/61158959/85928048-82eb3a00-b880-11ea-9ac8-8ae32550d0c1.png)
![alloy Pinda MES](https://user-images.githubusercontent.com/61158959/85928077-b7f78c80-b880-11ea-8310-b1353217b67a.png)

**Comment by guptaad** [comment]
Changing the priority to give higher precedence to the Sync_Len for PInda, Oswego and YJ.

**Comment by hebernogueira** [comment]
Hi, there is an info field on raw files which could be evaluated wether it is suitable or not.
Below an screenshot.

![image](https://user-images.githubusercontent.com/61158959/87671664-190bd500-c748-11ea-9755-54569b33c734.png)

**Comment by hebernogueira** [comment]
Hello @khancynthia28 , I believe this is not fixed, is it?
Or was this issue closed due to the lack of solution?
Thanks
