### ISSUE TITLE
coil_id mismatch - pinda HFM data

### ISSUE THREAD

**Issue by agrawalch** [novelis-prod/Digital-CoE-Operations-Data---Public#69]
@hebernogueira @guptaad 

The issue is that the coil_id=11638 value of 11719 in the coil_id column. The right value is 11638, but we see 11719 in the column cg_Gen_CoilId.

**Comment by hebernogueira** [comment]
Same as issue #67

**Comment by guptaad** [comment]
This is duplicate of #67. So closing this.
