### ISSUE TITLE
Oswego and PBA caster, melter and holder tables have different formats. Is there a reason?

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#7]
Oswego Caster table has 386 columns and Pinda Caster table has 562 columns. 
Oswego Melter table has 145 columns and Pinda Melter table has 183 columns.
Oswego Holder table has 128 columns and Pinda Holder table has 148 columns.
Why is there a difference?

**Comment by khancynthia28** [comment]
@amitdingareNovelis Closing this one and opening a new one stating issue as Alloy Code missing for YeongJu Remelt

**Comment by khancynthia28** [comment]
@RyanNovelis Hi Ryan, it is usually the caster where you'd expect to find the Alloy samples taken and recorded. That information doesn't come from Melter or Holder. If you do want to associate the Alloy info to the Holder tag values you'd have to query for the master_batch_ids associated with the Alloy and Timestamps you're looking for. Does that make sense?
