### ISSUE TITLE
YJ CM data for April 2020 is not available

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#71]
As per the digest sent out last Friday, Yeongju CM data for April is marked as complete. However, we do not find April 2020 data in the delta lake.
![Digest0626](https://user-images.githubusercontent.com/4303278/86154911-b1ac1f00-bad1-11ea-9c40-4084e1595bf3.jpg)

![image](https://user-images.githubusercontent.com/4303278/86154705-6c87ed00-bad1-11ea-8c24-8eb598e8de0b.png)

**Comment by guptaad** [comment]
@khancynthia28 @changhyucklee - as discussed today, please ensure that the data pipeline is actually finished before marking the completion. There are missing pieces in YJ data at this time.

**Comment by amitdingareNovelis** [comment]
Latest digest corrected this. Closing.
