### ISSUE TITLE
Yeongju Sync Length for CM is not populated.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#72]
None of the coils for YJ have sync length populated. We are planning to have a demo to YJ using EagleViz for which we will need this.

**Comment by guptaad** [comment]
Chirag finishing the Oswego first and then populated this for YJ.
ETA : Tuesday (7/7)

**Comment by agrawalch** [comment]
@changhyucklee @guptaad  @khancynthia28 @amitdingareNovelis 

Sync length code is complete for both OSW and YEJ.  

For YEJ: The entry and exit rolled length values require fix in the PDO for HRM, HFM and CM2.
![image](https://user-images.githubusercontent.com/53792688/86806587-01956380-c047-11ea-90be-4cb857fcbb4a.png)

A separate git-issue is opened for it and assigned to ChangHyuck.

sync_length values require retesting after PDO are fixed and iba files are sending right entry and exit rolled-lengths.

**Comment by amitdingareNovelis** [comment]
@agrawalch does this mean we have Sync length available for Oswego? If so, this is a good news.

**Comment by agrawalch** [comment]
@amitdingareNovelis 
Yes, sync length is available for Oswego. Please use sync length present only for HRM and HFM machine centers. For CM, we have seen that rolled-lengths are not correct.

![image](https://user-images.githubusercontent.com/53792688/86919177-d3bb2800-c0f5-11ea-9424-d904f410292a.png)
