### ISSUE TITLE
Exact same coil id appears in CM2 and CM3 for Yeongju

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#73]
![image](https://user-images.githubusercontent.com/4303278/86160020-2df63080-bad9-11ea-8c8a-a55a3e0ab05a.png)

**Comment by guptaad** [comment]
@amitdingareNovelis can you please elaborate a bit? Did you mean that the metal_code is different for the same coil ID in YJ?

**Comment by amitdingareNovelis** [comment]
Sorry! I should have been more clear. The first two columns belong to CM2 and next two to CM3. The metal code for CM2 is null and metal code for CM3 is populated. The coil ids are the same. In which case, will the coil id between CM2 and CM3 be the same?

**Comment by guptaad** [comment]
> Sorry! I should have been more clear. The first two columns belong to CM2 and next two to CM3. The metal code for CM2 is null and metal code for CM3 is populated. The coil ids are the same. In which case, will the coil id between CM2 and CM3 be the same?

Got it!  Thanks for explaining. 
@KrishnaMaddipati Please take a look why the CM2 metal code is null in YJ data.

**Comment by khancynthia28** [comment]
@amitdingareNovelis @KrishnaMaddipati Has this been resolved since the Metal Code update?

**Comment by amitdingareNovelis** [comment]
@KrishnaMaddipati or @agrawalch can you answer?

**Comment by KrishnaMaddipati** [comment]
@amitdingareNovelis @khancynthia28 This was resolved with the new metal code update. There are no coils for YeongJu with  default or null metal code values.

![image](https://user-images.githubusercontent.com/62263802/87271791-4e8f9480-c4a2-11ea-87e0-12d704ec8a8c.png)

**Comment by khancynthia28** [comment]
Closing the ticket. Please reopen if issue resurfaces.
