### ISSUE TITLE
For Yeongju, many coils exist in CM2 or CM3, but not in HFM. Does YJ CM get coils from other plants?

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#75]
![image](https://user-images.githubusercontent.com/4303278/86160973-8f6acf00-bada-11ea-927e-39610ae2c15e.png)

**Comment by guptaad** [comment]
@amitdingareNovelis YJ does not get coils from other plants. 

@changhyucklee I just checked and the data for CM only goes to the middle of Jun. Please check.

**Comment by changhyucklee** [comment]
I found that some of coils didn't uploaded to ADLS. I have re-check inventory and re-processing coil data which was not uploaded.

**Comment by khancynthia28** [comment]
Closing. Please reopen if issue resurfaces.
