### ISSUE TITLE
For Yeongju, many coils exist in HFM, but not in HRM

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#76]
![image](https://user-images.githubusercontent.com/4303278/86162714-3d777880-badd-11ea-874a-3f1a87ceb21f.png)

**Comment by changhyucklee** [comment]
@amitdingareNovelis Could you let me know your query statement?
I can find that upper coilid (which screen captured)  from opsentprodg2.yej_hrm table as below
%sql
select distinct year, month, day,cg_gen_coilid
from opsentprodg2.yej_hrm
where cg_gen_coilid in (
'S401888',
'S406805',
'S407523',
'S408738',
'S408793',
'S411171',
'S411861',
'S414476'
)
![image](https://user-images.githubusercontent.com/60994327/86357809-5af93d80-bca9-11ea-9eb5-1e46bf07878f.png)

**Comment by amitdingareNovelis** [comment]
@changhyucklee, I pasted a wrong screenshot by mistake. Here is the correct one

![image](https://user-images.githubusercontent.com/4303278/86368876-ba286500-bc4b-11ea-9b74-7a5c412cb7c0.png)

Also, here is my query.

(select tb1.cg_Gen_Coilid
from
(select distinct cg_Gen_Coilid
from
opsentprodg2.yej_hrm
where 
year= '2020') tb1
left outer join
(select distinct cg_Gen_Coilid
from
opsentprodg2.yej_hfm
where 
year= '2020') tb2
on tb1.cg_Gen_Coilid = tb2.cg_Gen_Coilid
where tb2.cg_Gen_Coilid is null)

**Comment by changhyucklee** [comment]
I found that some of coils didn't uploaded to ADLS. I have re-check inventory and re-processing coil data which was not uploaded.

**Comment by khancynthia28** [comment]
Closing. Please reopen if issue resurfaces.
