### ISSUE TITLE
Oswego CM is missing several days of data. Is that because the CM was down on those days?

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#77]
For CM72
For June,
1. First 9 days, and from 26th to 28th of June data is missing.
2. The numbers look suspiciously low.

![image](https://user-images.githubusercontent.com/4303278/86303078-b4456c00-bbd8-11ea-9bf4-624395b815ed.png)

For May,
![image](https://user-images.githubusercontent.com/4303278/86303201-21f19800-bbd9-11ea-81c5-7254cb5cb159.png)

For CM88
For June,
1. numbers look lower towards the end of the month
![image](https://user-images.githubusercontent.com/4303278/86303504-f7540f00-bbd9-11ea-97b4-238a74ccc168.png)

For May
![image](https://user-images.githubusercontent.com/4303278/86303274-59f8db00-bbd9-11ea-9050-fbded5c726aa.png)

**Comment by khancynthia28** [comment]
@zennet-novelis

**Comment by zennet-novelis** [comment]
CM72 had an outage between May 22 and June 10 where data was lost on the L2 file system.

The count of 1 on 2002-06-22 looks very suspicious. We had some problems between June 10 and June 22. I see 30 raw files in adls. I'll check that the June backfill was uploaded, then we can reload the delta tables. And check with what's in MIS and AGW.

**Comment by zennet-novelis** [comment]
For CM72 June 22, I can see 28 coil - pass combinations in ADLS. This appears related to issues around loading into the delta tables. Assigning @KrishnaMaddipati.

**Comment by zennet-novelis** [comment]
@amitdingareNovelis CM88 and CM72 were down on June 27, 28 and June 26, 27, 28 and produced zero coils.

**Comment by zennet-novelis** [comment]
@amitdingareNovelis There are three causes of this variation
1. Data available on ADLS but cannot load to enterprise zone because of missing fields like Entry Discard
2. Data on AGW that never made it to parquet in ADLS
3. Actual variation in coil output

We are working on correcting 1 and 2.
Here's a view into variation for the month of May based on files arriving to AGW.

```
CM72 200501/ 99
CM72 200502/ 64
CM72 200504/ 62
CM72 200505/ 64
CM72 200508/ 99
CM72 200509/ 79
CM72 200511/ 82
CM72 200512/ 108
CM72 200513/ 71
CM72 200514/ 19
CM72 200515/ 77
CM72 200516/ 70
CM72 200518/ 36
CM72 200519/ 103
CM72 200520/ 113
CM72 200521/ 22
CM72 200522/ 9

CM88 2020/05/01/ 82
CM88 2020/05/02/ 9
CM88 2020/05/05/ 61
CM88 2020/05/08/ 107
CM88 2020/05/09/ 59
CM88 2020/05/12/ 73
CM88 2020/05/13/ 15
CM88 2020/05/15/ 86
CM88 2020/05/16/ 41
CM88 2020/05/19/ 68
CM88 2020/05/20/ 26
CM88 2020/05/22/ 83
CM88 2020/05/23/ 72
CM88 2020/05/26/ 87
CM88 2020/05/27/ 20
CM88 2020/05/29/ 82
CM88 2020/05/30/ 114
```

**Comment by zennet-novelis** [comment]
@amitdingareNovelis Closing this question as resolved. Please reopen if you have additional concerns. Work to resolve the 1 and 2 will be done on #53
