### ISSUE TITLE
Pinda CM June numbers for certain days look suspiciously low. Please evaluate.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#78]
![image](https://user-images.githubusercontent.com/4303278/86304259-5e72c300-bbdc-11ea-903a-f1b3e0ffe9e0.png)

**Comment by khancynthia28** [comment]
@KrishnaMaddipati

**Comment by amitdingareNovelis** [comment]
Looked at this with Chirag. It appears that the coil count was what was produced. Closing.
