### ISSUE TITLE
Files from HFM not avaiable in cloud (01 and 02 July)

### ISSUE THREAD

**Issue by hebernogueira** [novelis-prod/Digital-CoE-Operations-Data---Public#79]
Hello  @guptaad 

Some files from the 1st and 2nd July are not in cloud. And some seems to be bad files.
@agrawalch did work on the pipeline yesterday but HFM was not running. 
After HFM restart, the issue was noticed.

Thanks,

Heber

![2020-07-01 20_07_29-Ephemeral Notebook Job (Run id_ 412196) - Databricks](https://user-images.githubusercontent.com/61158959/86356347-7846f100-bc42-11ea-938e-2a5f6bec54e6.png)
![2020-07-02 09_03_04-](https://user-images.githubusercontent.com/61158959/86356685-0622dc00-bc43-11ea-8b7a-defc3bcc6dfb.png)
![2020-07-01 20_07_29-Ephemeral Notebook Job (Run id_ 412196) - Databricks](https://user-images.githubusercontent.com/61158959/86356362-7da43b80-bc42-11ea-8824-4b3005cf9ad2.png)

![2020-07-01 20_08_27-Ephemeral Notebook Job (Run id_ 412461) - Databricks](https://user-images.githubusercontent.com/61158959/86356331-6feeb600-bc42-11ea-99c0-fa29756cf43d.png)

**Comment by agrawalch** [comment]
The pipeline is fixed and working. The data is present as of today. I am still observing the pipeline for 1 more week to make sure that everything is working as expected.

**Comment by agrawalch** [comment]
@hebernogueira 
Can you please confirm that pipeline is running well now and if that is the case then please close this issue.

**Comment by hebernogueira** [comment]
@agrawalch pipeline seems more stable now.
Thank you
