### ISSUE TITLE
Pinda coils missing between HFM and HRM

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#8]
4260 coils that exist in HFM do not exist in HRM for PBA.
36349 coils that exist in HRM do not exist in HFM for PBA.

**Comment by khancynthia28** [comment]
@amitdingareNovelis Does the issue still exist?

**Comment by khancynthia28** [comment]
Closing. Please open if issue re-surfaces.
