### ISSUE TITLE
YEJ - HRM and HFM - EntryRolledLength and ExitRolledLength values are wrong

### ISSUE THREAD

**Issue by agrawalch** [novelis-prod/Digital-CoE-Operations-Data---Public#82]
1) HRM: ExitRolledLength  values too high, correct values should be in the range of 100s, we see values in 16Ks range. (Red boxes in the screen shot below)
2) HFM: EntryRolledLength and ExitRolledLength looks wrong. (Green boxes in the screen shot below).
    2.1) Entry length should be around 100, we see entry lengths in 5Ks. 
    2.2) Exit length should be higher than entry length, we see reverse trend, exit length is lower than entry length.  

![image](https://user-images.githubusercontent.com/53792688/86601890-e6a3f000-bf6f-11ea-9b53-af67f8ac9888.png)

**Comment by changhyucklee** [comment]
I have discussed this with YeongJu automation engineer. He just know about address of signals and don't know how those expression has consisted. So I send to email to Roberto and Felipe to check this issue.

**Comment by changhyucklee** [comment]
For HRM, I have modified speed signals and then found that entry  / exit length was change to be reasonable.
I have applied this updated PDO file to ibaDatcorrdinator from today.

**Comment by changhyucklee** [comment]
For HFM,
After convert dg_F1_EnTable_Speed_Meas signal from RPM to m/s by fomular "[13:31]*0.305*PI()/60", I can get reasonable entry rolled length value as below.
I have applied this updated PDO file to ibaDatcorrdinator from today.
![image](https://user-images.githubusercontent.com/60994327/88363183-177e8480-cdba-11ea-9249-e5b6abab1115.png)
