### ISSUE TITLE
Many coils for Pinda CM from April onwards do not have metal code populated.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#84]
![image](https://user-images.githubusercontent.com/4303278/86803786-4d92d900-c044-11ea-9a91-e2c37bfbdd38.png)

712 coils to be precise.

@RyanNovelis you may need to rerun aggregations for these coils once the issue is fixed.

**Comment by amitdingareNovelis** [comment]
Adding @ethanchaNovelis for awareness.

**Comment by amitdingareNovelis** [comment]
Getting this fixed is important to us.

**Comment by guptaad** [comment]
@agrawalch @KrishnaMaddipati Please take a look at this.

**Comment by khancynthia28** [comment]
@amitdingareNovelis This seems to have been resolved. Can we close?

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87155027-3c3a0e80-c288-11ea-8fa9-5fa4eb00e134.png)

**Comment by amitdingareNovelis** [comment]
Closing.
