### ISSUE TITLE
2000+ coils in the _time tables for Pinda from April onwards do not have metal code populated.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#85]
![image](https://user-images.githubusercontent.com/4303278/86804810-428c7880-c045-11ea-9eef-805bbadb95ed.png)

**Comment by amitdingareNovelis** [comment]
Getting this fixed is important to us.

**Comment by KrishnaMaddipati** [comment]
@amitdingareNovelis  All the metal codes for pinda 2020 time data was updated. Please verify and close the ticket.

![image](https://user-images.githubusercontent.com/62263802/87528027-f6e85900-c65a-11ea-8551-3428c3eb18f6.png)

**Comment by khancynthia28** [comment]
![image](https://user-images.githubusercontent.com/34836475/87940374-7dd86f80-ca67-11ea-8a9e-595a0bf50dd9.png)

@amitdingareNovelis  Can we close?

**Comment by khancynthia28** [comment]
@amitdingareNovelis Hi Amit, closing this one for now. Please reopen if the issue still exists. Thanks.
