### ISSUE TITLE
Pass numbers for Pinda don't look right

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#86]

**Comment by amitdingareNovelis** [comment]
![image](https://user-images.githubusercontent.com/4303278/86809284-b7fa4800-c049-11ea-851c-832943c8742f.png)

**Comment by amitdingareNovelis** [comment]
@guptaad can we priortize this as well?

**Comment by guptaad** [comment]
#87 and this can be handled as the same issue.

**Comment by amitdingareNovelis** [comment]
The issue is still open.

**Comment by agrawalch** [comment]
CM3 decimal point pass_number is resolved.

For CM1 and CM2, we need additional column - PASS_NUMBER, from MES data.
I have opened a request in SNOW to add PASS_NUMBER in the MES data we receive for Pinda, Once we have this additional columns, we should be able to replace the many passes with sequence starting with 1 such as (1, 2, 3, 4 etc).

![image](https://user-images.githubusercontent.com/53792688/87345227-cb138900-c51d-11ea-8c3e-694f6142ffd6.png)

**Comment by BrentR2020** [comment]
REFER TO DUPLICATE IN ISSUE #87
