### ISSUE TITLE
Many different pass numbers exist for Pinda. Are these all valid?

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#87]
In the past, when we saw this, we were told that these pass numbers would be unified. Is that still applicable?

1 | CM3
10 | CM1
12 | CM1
13.595 | CM3
20 | CM1
25 | CM1
30 | CM1
40 | CM1
40 | CM2
50 | CM2
50 | CM1
60 | CM2
60 | CM1
70 | CM2
70 | CM1
80 | CM1
80 | CM2
85 | CM2
86 | CM2
87 | CM2
90 | CM1
90 | CM2
95 | CM2
96 | CM2
100 | CM2
100 | CM1
110 | CM2
120 | CM2
120 | CM1
130 | CM1
130 | CM2
140 | CM2
150 | CM2
160 | CM1
160 | CM2
170 | CM2
180 | CM2
180 | CM1
200 | CM1
220 | CM1

**Comment by guptaad** [comment]
@agrawalch this is the process sequence; we discussed to have the pass# in the data file.
Also, the 13.595 is back.

**Comment by agrawalch** [comment]
CM3 decimal point pass_number is resolved.

For CM1 and CM2, we need additional column - PASS_NUMBER, from MES data.
I have opened a request in SNOW to add PASS_NUMBER in the MES data we receive for Pinda, Once we have this additional columns, we should be able to replace the many passes with sequence starting with 1 such as (1, 2, 3, 4 etc). 

![image](https://user-images.githubusercontent.com/53792688/87345039-6f490000-c51d-11ea-979c-a0469769cf8c.png)

**Comment by amitdingareNovelis** [comment]
@RyanNovelis FYI. Are you seeing things differently?

**Comment by RyanNovelis** [comment]
@amitdingareNovelis I am seeing what you saw with the exception of CM3 only containing PassNumber 1.
