### ISSUE TITLE
Pinda sync length nan values

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#89]
I was working on filtering pinda coils by max sync length > 0 and min sync length > 0 per the suggestion of @agrawalch. I found numerous instances where min sync length was correct but max sync length was NaN. Please see below.

![image](https://user-images.githubusercontent.com/58708978/87076002-26c4d600-c1ef-11ea-9d5e-48e37973268d.png)
![image](https://user-images.githubusercontent.com/58708978/87076027-2e847a80-c1ef-11ea-88c6-f7236efe31e4.png)
![image](https://user-images.githubusercontent.com/58708978/87076057-37754c00-c1ef-11ea-9eed-503a1f84ca11.png)
![image](https://user-images.githubusercontent.com/58708978/87076076-3e9c5a00-c1ef-11ea-815b-fffbcd94e20a.png)

**Comment by agrawalch** [comment]
@RyanNovelis 
I think the max function doesn't eliminate NaNs, see image below. I checked on some coil_ids from HFM.
![image](https://user-images.githubusercontent.com/53792688/87082032-59270100-c1f8-11ea-83e0-410a21eae97c.png)

**Comment by RyanNovelis** [comment]
@agrawalch why are NaN values showing up in calculated sync length column, and would you suggest us drop the rows in which they show up as seen in the example given?

**Comment by agrawalch** [comment]
@RyanNovelis 
I think this is shown because there are NaNs in Length or ReverseLength index values. We use those index to calculate sync_length. The right approach would be to drop NaNs and then use sync_length.

**Comment by RyanNovelis** [comment]
@agrawalch Understood, thank you for let me know. I will follow that approach.

**Comment by amitdingareNovelis** [comment]
@RyanNovelis Let us know if it's okay to close this.

**Comment by RyanNovelis** [comment]
@amitdingareNovelis and @agrawalch Yes I will close this.

**Comment by amitdingareNovelis** [comment]
Sorry.. I should have validated this before. @agrawalch I am seeing NaNs in Sync Length. I understood that you wanted us to drop sync length = NaNs, but then the question is why don't you drop those yourselves? What is the point of keeping NaNs in the data when there isn't any value from it?

**Comment by guptaad** [comment]
@agrawalch to understand the source of NaNs; possibly remove the NaNs depending on the data points.

**Comment by amitdingareNovelis** [comment]
@agrawalch any update on this?

**Comment by agrawalch** [comment]
@amitdingareNovelis 
In the data-validation level-1 checks, this is fixed. Any NaNs present in LengthIndex or ReverseLengthIndex are removed. This will not create any NaNs in sync length. Update on historical data is pending. There is no timeline on this as there is no priority assigned to it for historical.

**Comment by khancynthia28** [comment]
Closing this as resolved. Please reopen if needed.
