### ISSUE TITLE
Should Unique combination exist for a metal code and coil id, pass number combination? This issue is becoming more common.

### ISSUE THREAD

**Issue by amitdingareNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#9]
We are finding that multiple rows exist for a unique combination of metal code, coilid and pass number. Could this be because something happened and the pass needs to be redone? If so, should the DE team keep values pertaining to the last row of that pass?

See an example below

![image](https://user-images.githubusercontent.com/4303278/79915093-56d0ba00-83f4-11ea-80a1-ba74339a259a.png)

**Comment by amitdingareNovelis** [comment]
@guptaad could we priortize this? I am seeing that this issue is becoming more common now. One potential solution we discussed is getting the coil id from the file name and not from what is populated.

**Comment by guptaad** [comment]
@amitdingareNovelis yes, we can and we need to reset some of the other priorities.
@agrawalch can you please take a look at this?

**Comment by khancynthia28** [comment]
Resolved.
