### ISSUE TITLE
Alloy Code missing from Yeong Ju Remelt data

### ISSUE THREAD

**Issue by khancynthia28** [novelis-prod/Digital-CoE-Operations-Data---Public#90]
PI data doesn't have a tag for Alloy built in. Will have to incorporate the info from MES.

**Comment by RyanNovelis** [comment]
@khancynthia28 another part of the issue #7 that did not get carried over is that pba_holder does not have an alloy column as well.

![image](https://user-images.githubusercontent.com/58708978/87808799-5c3d7500-c828-11ea-9b12-1b1d31ce64a4.png)

**Comment by khancynthia28** [comment]
Resolved. 

![image](https://user-images.githubusercontent.com/34836475/90666602-9e891600-e21b-11ea-8099-7c298624ff48.png)
