### ISSUE TITLE
Pinda HFM ADLS files found /not found

### ISSUE THREAD

**Issue by hebernogueira** [novelis-prod/Digital-CoE-Operations-Data---Public#91]
Hello,

Facing an issue with HFM files which I could not figure out the reason.
The flow has a first notebook (hfm_automatic_run) which seek new coils in ADLS, fills a coil status table and finally triggers an notebook run of the coils with status pending on the table. This second notebook will evaluate the rules for each coil.
![image](https://user-images.githubusercontent.com/61158959/87689345-7874df80-c75e-11ea-9125-03bc924024e7.png)

Then in the notebook hfm_alarm_gen_v2, I look for the coil path again. The notebook finds it, but when reading the parquet an exception is retrieved saying that path does not exist.
![image](https://user-images.githubusercontent.com/61158959/87689595-cd185a80-c75e-11ea-9a24-1d89d749a856.png)
![image](https://user-images.githubusercontent.com/61158959/87689613-d1447800-c75e-11ea-9df9-184c41f13af8.png)

In fact, Microsoft Azure Storage Explorer (MASE) does not show up the file.
![image](https://user-images.githubusercontent.com/61158959/87689867-1a94c780-c75f-11ea-99a2-ff9fd52b65d6.png)

The point here, how is it possible for the code to 'see' the parquet and path files, while MASE does not?
It seems that the process of uploading files to ADLS firstly writes/defines the path and later upload the file.
In the last screenshot, when looking for timestamps it seems that files were uploaded as a batch.
I am also attaching notebooks here as zip

[Notebook_2020-07-16.zip](https://github.com/novelis-prod/Digital-CoE-Operations-Data---Public/files/4932445/Notebook_2020-07-16.zip)

Thanks Heber

**Comment by hebernogueira** [comment]
Another evidences:
Last coil in MASE: 50001
![image](https://user-images.githubusercontent.com/61158959/87692304-fa1a3c80-c761-11ea-8e4e-f6f8cd844f15.png)

Notebook found others:
![image](https://user-images.githubusercontent.com/61158959/87692408-1ae29200-c762-11ea-906d-986a2395e9f5.png)

AGW:
![image](https://user-images.githubusercontent.com/61158959/87692453-27ff8100-c762-11ea-8ffa-8a486d32d4f6.png)

Tks

**Comment by hebernogueira** [comment]
Providing more evidences:
![image](https://user-images.githubusercontent.com/61158959/87733618-af6ee380-c7a6-11ea-9414-20e8a825ff24.png)

**Comment by hebernogueira** [comment]
Adding more curious info:
Note that coils which were uploaded after the 'batch' of 11 am were processed successfully in Databricks.
Unfortunatelly the query shows top 10 and where clause is not showing the last 3 coils which were uploaded. But is possible to see that two of them were processed successfully.

![image](https://user-images.githubusercontent.com/61158959/87787966-e7ac0b80-c812-11ea-9347-ba39b7f8d44a.png)

![image](https://user-images.githubusercontent.com/61158959/87787990-ee3a8300-c812-11ea-921b-8052548d858e.png)

**Comment by khancynthia28** [comment]
@hebernogueira Can we close this now?

**Comment by hebernogueira** [comment]
@khancynthia28 Hello Cynthia. The main point here is to figure out how Databricks 'find' files in ADLS with one notebook whilst the second notebook and Azure Storage Explorer don't.
It is super strange. 
The pipeline brake was noticed during the investigation.
This is not affecting the project anymore but I feel that will happen again somewhere in future. 

So if there is no interest about going ahead with this investigation, then you can close.
If it happens again, then I can reopen the issue.
Thank you.

Heber

**Comment by khancynthia28** [comment]
@hebernogueira Hi Heber. that sounds good. I'm closing it for now. Please reopen if the error occurs again and we can take it to Databricks. Thanks.
