### ISSUE TITLE
dg_EnThick_ThicknessDeviation_Relative_Meas pba_hfm null/NaN values

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#93]
We are seeing null values for the column of dg_EnThick_ThicknessDeviation_Relative_Meas

![image](https://user-images.githubusercontent.com/58708978/88427134-58799780-cdc0-11ea-92af-9705bdd80e17.png)
![image](https://user-images.githubusercontent.com/58708978/88427162-629b9600-cdc0-11ea-809d-83b4f2d56b83.png)
![image](https://user-images.githubusercontent.com/58708978/88427187-6fb88500-cdc0-11ea-9fdc-4ae50db427e4.png)

**Comment by guptaad** [comment]
@agrawalch can you please check on this signal? Given this is a dg signal, I take that this should come straight from L2 and so we are possibly missing the catalog mapping of this signal.

@RyanNovelis - Just a quick training point when joining the machine center level tables. You always want to use the sync-length in the join statement. What you are doing here is a cartesian and it would take a long time, and also cause performance issues. You join should always be on "mc1.coilid = mc2.coild and mc1.sync_len = mc2.sync_len". Can you please ensure?

**Comment by amitdingareNovelis** [comment]
> @agrawalch can you please check on this signal? Given this is a dg signal, I take that this should come straight from L2 and so we are possibly missing the catalog mapping of this signal.
> 
> @RyanNovelis - Just a quick training point when joining the machine center level tables. You always want to use the sync-length in the join statement. What you are doing here is a cartesian and it would take a long time, and also cause performance issues. You join should always be on "mc1.coilid = mc2.coild and mc1.sync_len = mc2.sync_len". Can you please ensure?

Hi Adarsh, agreed on the performance. Appreciate if you can get this issue fixed by Monday. We are planning on using this example (provided to us by Roberto) for the training on Tuesday.

**Comment by RyanNovelis** [comment]
@guptaad Yes everything that isn't being aggregated to the coil based level, so one row per coil,  is also being joined by sync_length as well.

**Comment by BrentR2020** [comment]
Moved to Azure DevOps

**Comment by khancynthia28** [comment]
Closing this. Please see DevOps board for updates.
