### ISSUE TITLE
Pinda tables not partitioned or contain more than just partitions within opsentprodg2

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#94]
Went to look at which dates the pinda tables had within opsentprodg2 and found that many tables are no longer partitioned by anything, or contained partitions and parquet files outside of those partitions

![image](https://user-images.githubusercontent.com/58708978/88690538-c4624580-d0c9-11ea-9123-9794528ccd63.png)
![image](https://user-images.githubusercontent.com/58708978/88690581-cd531700-d0c9-11ea-8b78-3214dd93a4a2.png)
![image](https://user-images.githubusercontent.com/58708978/88690616-d6dc7f00-d0c9-11ea-9f6d-88180f169774.png)
![image](https://user-images.githubusercontent.com/58708978/88690641-de9c2380-d0c9-11ea-9df9-123f2c945b0a.png)
![image](https://user-images.githubusercontent.com/58708978/88690682-e78cf500-d0c9-11ea-9448-3de8c44b4ea3.png)
![image](https://user-images.githubusercontent.com/58708978/88690727-f1aef380-d0c9-11ea-8b1c-454029682fae.png)
![image](https://user-images.githubusercontent.com/58708978/88690744-fa072e80-d0c9-11ea-9a2f-002a04886ffd.png)
![image](https://user-images.githubusercontent.com/58708978/88690776-02f80000-d0ca-11ea-8dee-71a7e15835af.png)
![image](https://user-images.githubusercontent.com/58708978/88690819-0f7c5880-d0ca-11ea-9e55-aaac13d23bc2.png)
![image](https://user-images.githubusercontent.com/58708978/88690848-16a36680-d0ca-11ea-93a4-30d40dfbfa26.png)

**Comment by khancynthia28** [comment]
Closing this one with the new data load. Please reopen if issue re-surfaces.
