### ISSUE TITLE
Incorrect cg_Gen_PassNumber for pba_cm3

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#96]
Incorrect cg_Gen_PassNumber for pba_cm3, 12.215.

![image](https://user-images.githubusercontent.com/58708978/89316486-30085d80-d64a-11ea-809b-f2a2be51aa0a.png)

**Comment by BrentR2020** [comment]
Moved to Azure DevOps
