### ISSUE TITLE
_time delta tables are missing days Pinda

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#97]
Multiple days are missing from the time delta tables within Pinda

All of August

Multiple days within each other month for multiple machine centers

Parquet files are present within landing standard

Parquet files: example month 7 hfm
![image](https://user-images.githubusercontent.com/58708978/89553601-ba33fb80-d7db-11ea-98fd-01f2636b3c9b.png)

Delta table: example month 7 hfm
![image](https://user-images.githubusercontent.com/58708978/89553625-c28c3680-d7db-11ea-8f5f-68af297c7e5f.png)

**Comment by zhiyu-novelis** [comment]
Additionally, for those dates present in the delta table, some time windows are also missing. E.g. 07-20 before 18:30
