### ISSUE TITLE
Finding multiple alloys per one master_batch_id pinda caster

### ISSUE THREAD

**Issue by RyanNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#98]
I found numerous instances where multiple alloys are associated per one master_batch_id

![image](https://user-images.githubusercontent.com/58708978/89554323-b654a900-d7dc-11ea-87a2-da40a7eb67b6.png)

[multi_alloy_batch_id.xlsx](https://github.com/novelis-prod/Digital-CoE-Operations-Data---Public/files/5036135/multi_alloy_batch_id.xlsx)

**Comment by khancynthia28** [comment]
Multiple alloys for one batch is created when some rows get updated with data from MES. MES has more accurate info for alloy. Ex: PI would capture Alloy as 5182 and MES would capture it as 5182M which is more accurate (5182M is a subset of 5182). Therefore, in every case of duplicate alloy, the one from MES (with letter in the end should be adopted).
