### ISSUE TITLE
Suspicion on cg_Gen_PassNumber only being 1 for Pinda CM3 for the month of April, May and June

### ISSUE THREAD

**Issue by ethanchaNovelis** [novelis-prod/Digital-CoE-Operations-Data---Public#99]
If you could look into this, that'd be greatly appreciated.

![image](https://user-images.githubusercontent.com/60716978/90037220-f232b700-dc91-11ea-9c78-f73c101c48e9.png)

Tagging: @LunaZhangNovelis

**Comment by amitdingareNovelis** [comment]
CM3 will have only one pass.
